server:
  port: 8089

Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmanagementsys?serverTimezone=GMT%2b8
    username: root
    password: "123"



#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.example.springboot.mybatis.entity
## 应用服务 WEB 访问端口
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 配置文件上传路径
file:
  upload-dir: C:/Users/lenovo/Desktop/BookManagementSys/Data/userfile



